[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = {version = "4.0", features = ["derive"]}
jemallocator = "0.5.0"


[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
